session_id: TODO
app_deadline: null
blocks:
- b0:
    type: CL
    duration: 500
    CS: null
- b1:
    type: QC
    duration: 380000
    CS: 1
- b2:
    type: QL
    duration: 20000
    CS: 1
- b3:
    type: QC
    duration: 380000
    CS: 1
- b4:
    type: QL
    duration: 20000
    CS: 1
- b5:
    type: CL
    duration: 2500
    CS: 1
- b6:
    type: CC
    duration: 100000
    CS: 1
- b7:
    type: CL
    duration: 4000
    CS: 1
