session_id: TODO
app_deadline: null
blocks:
- b0:
    type: CL
    duration: 100000
    CS: null
- b1:
    type: QC
    duration: 20000000
    CS: 1
- b2:
    type: QL
    duration: 1720000
    CS: 1
- b3:
    type: CC
    duration: 10000000
    CS: 1
- b4:
    type: CC
    duration: 10000000
    CS: 1
- b5:
    type: QL
    duration: 940000
    CS: 1
- b6:
    type: QC
    duration: 20000000
    CS: 1
- b7:
    type: QL
    duration: 1160000
    CS: 1
- b8:
    type: CL
    duration: 200000
    CS: null
