session_id: TODO
app_deadline: 1500000
blocks:
- b0:
    type: CL
    duration: 500
    CS: null
- b1:
    type: QC
    duration: 500000
    CS: 1
- b2:
    type: CC
    duration: 100000
    CS: 1
- b3:
    type: CC
    duration: 100000
    CS: 1
- b4:
    type: QL
    duration: 19000
    CS: 1
- b5:
    type: QC
    duration: 500000
    CS: 1
- b6:
    type: QL
    duration: 221000
    CS: 1
- b7:
    type: CL
    duration: 1000
    CS: null
