session_id: TODO
app_deadline: null
blocks:
- b0:
    type: CL
    duration: 100000
    CS: null
- b1:
    type: QC
    duration: 20000000
    CS: 1
- b2:
    type: QL
    duration: 600000
    CS: 1
- b3:
    type: QC
    duration: 20000000
    CS: 2
- b4:
    type: QL
    duration: 600000
    CS: 2
- b5:
    type: QC
    duration: 20000000
    CS: 3
- b6:
    type: QL
    duration: 600000
    CS: 3
- b7:
    type: CL
    duration: 300000
    CS: null
- b8:
    type: CC
    duration: 10000000
    CS: null
- b9:
    type: CC
    duration: 10000000
    CS: null
- b10:
    type: CC
    duration: 10000000
    CS: null
- b11:
    type: CL
    duration: 600000
    CS: null
